version: '3.8'

services:
  auth-service:
    build: .
    container_name: moydate-auth
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DATABASE_URL=postgresql://moydate:moydate_secret@postgres:5432/moydate_auth
      - REDIS_URL=redis://redis:6379
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    networks:
      - moydate-network

  postgres:
    image: postgres:16-alpine
    container_name: moydate-auth-db
    environment:
      - POSTGRES_USER=moydate
      - POSTGRES_PASSWORD=moydate_secret
      - POSTGRES_DB=moydate_auth
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - moydate-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U moydate"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: moydate-auth-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - moydate-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
  redis-data:

networks:
  moydate-network:
    driver: bridge
