// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://juzpcvhmiaxswiibicol.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp1enBjdmhtaWF4c3dpaWJpY29sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzMjg5NTgsImV4cCI6MjA3MzkwNDk1OH0.Osq-Wn5YE1nVZbRv87skH_ghkTKW_nRcjBqsA24OvQs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});